name: remit
description: Dart implementation of Remit.
version: 0.0.0
publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    http: ^1.1.0
    shelf: ^1.4.1
    shelf_router: ^1.1.4

dev_dependencies:
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git
